
AddonForThanksForPosts_controller:
    path: /AddonForThanksForPosts/{action}/{poster}/{forum}/{topic}/{post}
    defaults: { _controller: alg.AddonForThanksForPosts.thanks_ajax_handler:main }
    requirements:
        post: \d+
