imports:
    - { resource: tables.yml }

services:
    alg.AddonForThanksForPosts.thanks_ajax_handler:
        class: alg\AddonForThanksForPosts\controller\thanks_ajax_handler
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
            - @request
            - %core.table_prefix%
            - %tables.thanks%
            - %tables.users%
            - %tables.posts%
            - @?gfksx.ThanksForPosts.helper
